### ISSUE TITLE
Shedlock 4.0.0 locks schedule but does not execute

### ISSUE THREAD

**Issue by maartenvanheek** [lukas-krecan/ShedLock#175]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. shedlock v4.0.0
2. shedlock-provider-jdbc-template v4.0.0
3. Config:
```
@Configuration
@EnableScheduling
@EnableSchedulerLock(defaultLockAtMostFor = "30s")
public class SchedulingConfiguration {
    @Bean
    public TaskScheduler taskScheduler() {
        return new ConcurrentTaskScheduler();
    }

    @Bean
    public LockProvider lockProvider(DataSource dataSource) {
        // specify SCHEMA.tableName to prevent 'table or view does not exist' for database user with permissions
        return new JdbcTemplateLockProvider(dataSource, "SCHEMA_NAME.shedlock");
    }
}
```

Implementation:
```
@Component
public class SomeImplementingService {
    @Scheduled(cron = "${cron}")
    @SchedulerLock(name = "uniqueName", lockAtLeastFor = "1m", lockAtMostFor = "15m")
    @Transactional
    public void scheduledMethod() {
        someMethod.performAction();
        // includes log line
    }
}
```
4. ShedLock logs
n/a but I have application logs
```
2019-12-04 17:16:00,004 [pool-5-thread-1] DEBUG org.springframework.beans.factory.support.AbstractBeanFactory Returning cached instance of singleton bean 'lockProvider'
2019-12-04 17:16:00,005 [pool-5-thread-1] DEBUG org.springframework.jdbc.core.JdbcTemplate Executing prepared SQL statement [UPDATE SCHEMA.shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]

2019-12-04 17:16:00,010 [pool-5-thread-1] DEBUG net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor Locked 'uniqueName', lock will be held at most until 2019-12-04T16:31:00.004Z
2019-12-04 17:16:00,011 [pool-5-thread-1] DEBUG org.springframework.beans.factory.support.AbstractBeanFactory Returning cached instance of singleton bean 'lockProvider'
2019-12-04 17:16:00,011 [pool-5-thread-1] DEBUG org.springframework.jdbc.core.JdbcTemplate Executing prepared SQL statement [UPDATE SCHEMA.shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]
2019-12-04 17:16:00,012 [pool-5-thread-1] DEBUG XXX creating new proxy around given statement object: xyz.StatementDecoratorInterceptor$StatementProxy[Proxy=1291751840; Sql=UPDATE SCHEMA.shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?; Delegate=oracle.jdbc.driver.OraclePreparedStatementWrapper@6c95158b; Connection=DisposableConnectionFacade[null]]
2019-12-04 17:16:00,014 [pool-5-thread-1] DEBUG net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor Not executing 'uniqueName'. It's locked.
2019-12-04 17:16:00,014 [pool-5-thread-1] DEBUG org.springframework.jdbc.core.JdbcTemplate Executing prepared SQL statement [UPDATE SCHEMA.shedlock SET lock_until = ? WHERE name = ?]
2019-12-04 17:16:00,015 [pool-5-thread-1] DEBUG XXX creating new proxy around given statement object: xyz.StatementDecoratorInterceptor$StatementProxy[Proxy=981941923; Sql=UPDATE SCHEMA.shedlock SET lock_until = ? WHERE name = ?; Delegate=oracle.jdbc.driver.OraclePreparedStatementWrapper@58dcda9a; Connection=DisposableConnectionFacade[null]]
2019-12-04 17:16:00,018 [pool-5-thread-1] DEBUG net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor Task finished, lock 'uniqueName' will be released at 2019-12-04T16:17:00.004Z
```

... there is no mention of my scheduled task being executed. Application log line about activity is missing. Also I checked and the action is indeed not performed.

**Expected behavior**
My scheduled method performed its action and logs the result. Shedlock writes a lock + release time to database

**Actual behavior**
Shedlock prevents execution and instead logs `Not executing 'uniqueName'. It's locked.` However, Shedlock succesfully writes lock to database and afaik changes the end time after 'finishing' the task

This is on a test environment with only one node active, so no concurrency here. I did not implement a ScheduledLockConfiguration because I understand that `ScheduledLockConfigurationBuilder` is deprecated. Should't shedlock intercept Spring's `ConcurrentTaskScheduler' automatically, or do I need to implement additional config?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I will try to reproduce it, which version of Spring/Spring Boot do you use?

According to the log you have provided, the lock is applied but it somehow called itself recursively, which is strange. 

I assume that XXX was reference to your class.

**Comment by maartenvanheek** [comment]
XXX removed for possible information disclosure. I clarified the right part of those logs a bit by pasting back original content, as well as the `SomeImplementingService ` class declaration.

But XXX refers to some internal util class, not SomeImplementationService if that's  what you mean.

This application is based on spring (not boot) 5.0.12.RELEASE

**Comment by maartenvanheek** [comment]
Edit: I have to verify on Monday whether my deployment actually succeeded with regards to transactional

**Comment by lukas-krecan** [comment]
Thanks a lot. ShedLock 4 by default uses AOP proxy and it seems that the proxy got applied twice. So the first proxy got the lock and the second did not since it was already locked. I will make the lock recurrent so it does not happen.

**Comment by lukas-krecan** [comment]
Can you please try version 4.0.1

**Comment by Dubems-zenjob** [comment]
Version 4.0.0 does not also work for me, likewise version 4.0.1 nor version 3.0.0

**Comment by maartenvanheek** [comment]
Schedule is now executed wit 4.0.1. I still have to test it in a multi node environment, but this issue is resolved. Thank you.

**Comment by Dubems-zenjob** [comment]
Tried with the new version **4.0.1** but still get the same error: Tried on Spring boot version **2.1.4**

```
Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@58460505]
2019-12-09 16:02:02.902 DEBUG 84537 --- [    Test worker] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2019-12-09 16:02:02.902 DEBUG 84537 --- [    Test worker] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(190351436<open>)]
2019-12-09 16:02:02.905 DEBUG 84537 --- [    Test worker] o.s.orm.jpa.JpaTransactionManager        : Closing JPA EntityManager [SessionImpl(190351436<open>)] after transaction
2019-12-09 16:02:03.038 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Creating new transaction with name [null]: PROPAGATION_REQUIRES_NEW,ISOLATION_DEFAULT
2019-12-09 16:02:03.040 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Acquired Connection [HikariProxyConnection@808181320 wrapping org.postgresql.jdbc.PgConnection@128ec76a] for JDBC transaction
2019-12-09 16:02:03.040 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Switching JDBC Connection [HikariProxyConnection@808181320 wrapping org.postgresql.jdbc.PgConnection@128ec76a] to manual commit
2019-12-09 16:02:03.040 DEBUG 84537 --- [   scheduling-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL update
2019-12-09 16:02:03.040 DEBUG 84537 --- [   scheduling-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [UPDATE shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]
2019-12-09 16:02:03.042 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Initiating transaction commit
2019-12-09 16:02:03.042 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Committing JDBC transaction on Connection [HikariProxyConnection@808181320 wrapping org.postgresql.jdbc.PgConnection@128ec76a]
2019-12-09 16:02:03.043 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Releasing JDBC Connection [HikariProxyConnection@808181320 wrapping org.postgresql.jdbc.PgConnection@128ec76a] after transaction
2019-12-09 16:02:03.043 DEBUG 84537 --- [   scheduling-1] n.j.s.core.DefaultLockingTaskExecutor    : Not executing 'AppMetricsConfig.update'. It's locked.
2019-12-09 16:02:03.043 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Creating new transaction with name [null]: PROPAGATION_REQUIRES_NEW,ISOLATION_DEFAULT
2019-12-09 16:02:03.043 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Acquired Connection [HikariProxyConnection@287182511 wrapping org.postgresql.jdbc.PgConnection@128ec76a] for JDBC transaction
2019-12-09 16:02:03.044 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Switching JDBC Connection [HikariProxyConnection@287182511 wrapping org.postgresql.jdbc.PgConnection@128ec76a] to manual commit
2019-12-09 16:02:03.044 DEBUG 84537 --- [   scheduling-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL update
2019-12-09 16:02:03.044 DEBUG 84537 --- [   scheduling-1] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [UPDATE shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]
2019-12-09 16:02:03.045 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Initiating transaction commit
2019-12-09 16:02:03.045 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Committing JDBC transaction on Connection [HikariProxyConnection@287182511 wrapping org.postgresql.jdbc.PgConnection@128ec76a]
2019-12-09 16:02:03.045 DEBUG 84537 --- [   scheduling-1] o.s.j.d.DataSourceTransactionManager     : Releasing JDBC Connection [HikariProxyConnection@287182511 wrapping org.postgresql.jdbc.PgConnection@128ec76a] after transaction
```

**Comment by lukas-krecan** [comment]
@Dubems-zenjob Please go through troubleshooting section of README (I especially recommend checking the contents of the shedlock table) and if it does not help, please file a new issue.

**Comment by Santoshv1986** [comment]
Hi,
I am getting below error, I am using shedlock feature.


2021-09-20 08:01:00.003 ERROR 30286 --- [ThreadPoolTaskScheduler-9] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task. org.springframework.dao.TransientDataAccessResourceException: UpdateLock; SQL [UPDATE MY_SHED_LOCK SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]; pdtCp - Connection is not available, request timed out after 60000ms.; nested exception is java.sql.SQLTransientConnectionException: pdtCp - Connection is not available, request timed out after 60000ms.
--



</body>
</html>

**Comment by Santoshv1986** [comment]
and it is saying connection is not available, even i increased connections in pool.Please help me out what would be the issue
